# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_richmetadata', [dirname(__file__)])
        except ImportError:
            import _richmetadata
            return _richmetadata
        if fp is not None:
            try:
                _mod = imp.load_module('_richmetadata', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _richmetadata = swig_import_helper()
    del swig_import_helper
else:
    import _richmetadata
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class RichMetadataHelper(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RichMetadataHelper, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RichMetadataHelper, name)
    __repr__ = _swig_repr
    def initHelper(self, *args): return _richmetadata.RichMetadataHelper_initHelper(self, *args)
    def destroyHelper(self): return _richmetadata.RichMetadataHelper_destroyHelper(self)
    def isCoreMetadata(self): return _richmetadata.RichMetadataHelper_isCoreMetadata(self)
    def isAdvertisingMetadata(self): return _richmetadata.RichMetadataHelper_isAdvertisingMetadata(self)
    def isPaymentMetadata(self): return _richmetadata.RichMetadataHelper_isPaymentMetadata(self)
    def isScalabilityMetadata(self): return _richmetadata.RichMetadataHelper_isScalabilityMetadata(self)
    def getMainTitle(self): return _richmetadata.RichMetadataHelper_getMainTitle(self)
    def getSeriesTitle(self): return _richmetadata.RichMetadataHelper_getSeriesTitle(self)
    def getEpisodeTitle(self): return _richmetadata.RichMetadataHelper_getEpisodeTitle(self)
    def getDescription(self): return _richmetadata.RichMetadataHelper_getDescription(self)
    def getOriginator(self): return _richmetadata.RichMetadataHelper_getOriginator(self)
    def getProvider(self): return _richmetadata.RichMetadataHelper_getProvider(self)
    def getLocation(self): return _richmetadata.RichMetadataHelper_getLocation(self)
    def getCreationTime(self): return _richmetadata.RichMetadataHelper_getCreationTime(self)
    def getGenre(self): return _richmetadata.RichMetadataHelper_getGenre(self)
    def getLanguage(self): return _richmetadata.RichMetadataHelper_getLanguage(self)
    def getCaptionLanguage(self): return _richmetadata.RichMetadataHelper_getCaptionLanguage(self)
    def getSubtitleLanguage(self): return _richmetadata.RichMetadataHelper_getSubtitleLanguage(self)
    def getAgeAppropriateness(self): return _richmetadata.RichMetadataHelper_getAgeAppropriateness(self)
    def getDuration(self): return _richmetadata.RichMetadataHelper_getDuration(self)
    def getContentType(self): return _richmetadata.RichMetadataHelper_getContentType(self)
    def getFileFormat(self): return _richmetadata.RichMetadataHelper_getFileFormat(self)
    def getFileSize(self): return _richmetadata.RichMetadataHelper_getFileSize(self)
    def getBitRate(self): return _richmetadata.RichMetadataHelper_getBitRate(self)
    def getVisualCoding(self): return _richmetadata.RichMetadataHelper_getVisualCoding(self)
    def getWidth(self): return _richmetadata.RichMetadataHelper_getWidth(self)
    def getHeight(self): return _richmetadata.RichMetadataHelper_getHeight(self)
    def getAspectRatio(self): return _richmetadata.RichMetadataHelper_getAspectRatio(self)
    def getFrameRate(self): return _richmetadata.RichMetadataHelper_getFrameRate(self)
    def getAudioCoding(self): return _richmetadata.RichMetadataHelper_getAudioCoding(self)
    def getAudioChannels(self): return _richmetadata.RichMetadataHelper_getAudioChannels(self)
    def getBusinessModel(self): return _richmetadata.RichMetadataHelper_getBusinessModel(self)
    def isLiveContent(self): return _richmetadata.RichMetadataHelper_isLiveContent(self)
    def isAdvertisingAllowed(self): return _richmetadata.RichMetadataHelper_isAdvertisingAllowed(self)
    def getCircularContent(self): return _richmetadata.RichMetadataHelper_getCircularContent(self)
    def getAdType(self): return _richmetadata.RichMetadataHelper_getAdType(self)
    def getStreamingType(self): return _richmetadata.RichMetadataHelper_getStreamingType(self)
    def getAdFormat(self): return _richmetadata.RichMetadataHelper_getAdFormat(self)
    def getTargetGroupAge(self): return _richmetadata.RichMetadataHelper_getTargetGroupAge(self)
    def getTargetGroupCountry(self): return _richmetadata.RichMetadataHelper_getTargetGroupCountry(self)
    def getTargetGroupGender(self): return _richmetadata.RichMetadataHelper_getTargetGroupGender(self)
    def getContentFormatAspectRatio(self): return _richmetadata.RichMetadataHelper_getContentFormatAspectRatio(self)
    def getContentFormatFramerate(self): return _richmetadata.RichMetadataHelper_getContentFormatFramerate(self)
    def getPrice(self): return _richmetadata.RichMetadataHelper_getPrice(self)
    def getCurrency(self): return _richmetadata.RichMetadataHelper_getCurrency(self)
    def getPaymentId(self): return _richmetadata.RichMetadataHelper_getPaymentId(self)
    def acceptDonations(self): return _richmetadata.RichMetadataHelper_acceptDonations(self)
    def getAdvancedInfos(self): return _richmetadata.RichMetadataHelper_getAdvancedInfos(self)
    def getVectors(self): return _richmetadata.RichMetadataHelper_getVectors(self)
    def __init__(self): 
        this = _richmetadata.new_RichMetadataHelper()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _richmetadata.delete_RichMetadataHelper
    __del__ = lambda self : None;
RichMetadataHelper_swigregister = _richmetadata.RichMetadataHelper_swigregister
RichMetadataHelper_swigregister(RichMetadataHelper)



